"""empty message

Revision ID: 3357d542310e
Revises: 
Create Date: 2020-03-18 14:37:20.209458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3357d542310e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temperature', sa.String(length=5), nullable=False),
    sa.Column('humidity', sa.String(length=5), nullable=False),
    sa.Column('smoke', sa.String(length=5), nullable=False),
    sa.Column('time', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_data')
    # ### end Alembic commands ###
