"""add table

Revision ID: fff9d411e8ea
Revises: 3357d542310e
Create Date: 2020-03-28 16:16:04.935479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff9d411e8ea'
down_revision = '3357d542310e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home_bedroom_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temperature', sa.String(length=5), nullable=False),
    sa.Column('humidity', sa.String(length=5), nullable=False),
    sa.Column('smoke', sa.String(length=5), nullable=False),
    sa.Column('time', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_kitchen_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temperature', sa.String(length=5), nullable=False),
    sa.Column('humidity', sa.String(length=5), nullable=False),
    sa.Column('smoke', sa.String(length=5), nullable=False),
    sa.Column('time', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_kitchen_data')
    op.drop_table('home_bedroom_data')
    # ### end Alembic commands ###
